version: '3'

services:

  sudoku:
    container_name: sudoku
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #- 8095:80

networks:
  default:
    external:
      name: mrtimeey
